apiVersion: apps/v1
kind: Deployment
metadata:
  name: vollmed
  labels:
    app: vollmed
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vollmed
  template:
    metadata:
      labels:
        app: vollmed
    spec:
      containers:
      - name: vollmed-api
        image: maads2319/vollmed-api:1
        ports:
        - containerPort: 3000

        env:
          - name: DB_DATABASE #Aqeui nós colocamos o nome, pode ser qualquer nome
            valueFrom:
              configMapKeyRef:
                name: dados #Aqui o nome do configmap
                key: DB_DATABASE  #Nome da variavel que quer puxar
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: dados
                key: DB_HOST
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: senhas
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: senhas
                key: DB_PASSWORD

