apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-vollmed
spec: 
  type: LoadBalancer
  selector:
    app: 
  ports:
    - port: 3000 
      targetPort: 3000
      nodePort: 30000 #30000 - 32767 - Qual porta iremos expor, podemos escolher uma entre essa faixa