apiVersion: v1
kind: Service
metadata:
  name: nodeport-vollmed
spec: 
  type: nodeport
  selector:
    app: vollmed
  ports:
    - port: 3000 
      targetPort: 3000
      nodePort: 30000 #30000 - 32767 - Qual porta iremos expor, podemos escolher uma entre essa faixa